- name: "Ensures {{ cert_path }} dir exists"
  file: path="{{ cert_path }}" state=directory

- name: Copy certs
  copy: 
    src: "{{ item }}"
    dest: "{{ cert_path }}/"
    owner: openldap
    group: ssl-cert
    mode: 640
  with_fileglob:
    - '{{ local_cert_path }}/*'

- name: Fix certs permissions
  file: path="{{ cert_path }}" owner=openldap group=ssl-cert mode=0740 state=directory recurse=yes

- name: Render template directory-config-tls.ldif
  template: 
    src: roles/{{role_name}}/templates/directory-config-tls.ldif
    dest: "{{ tmp_dir }}/directory-config-tls.ldif"

- name: Apply Directory config TLS
  command: "ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ tmp_dir }}/directory-config-tls.ldif"

- name: Render template directory-config-tls-policy.ldif
  template: 
    src: roles/{{role_name}}/templates/directory-config-tls-policy.ldif
    dest: "{{ tmp_dir }}/directory-config-tls-policy.ldif"

- name: Apply TLS client policy
  command: "ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ tmp_dir }}/directory-config-tls-policy.ldif"

- name: "enable ldaps://"
  replace:
    path: /etc/default/slapd
    regexp: 'ldap:///'
    replace: 'ldap://127.0.0.1:389/'
    backup: yes
  when: disable_389_port == True

- name: "Disable ldap:// and enable ldaps://"
  replace:
    path: /etc/default/slapd
    regexp: 'ldapi:///'
    replace: 'ldapi:/// ldaps:///'
    backup: yes
  when: enable_ldaps == True
