# unique overlay
- name: Render template unique-overlay.ldif
  template:
    src: roles/{{role_name}}/templates/unique-overlay.ldif
    dest: "{{ tmp_dir }}/unique-overlay.ldif"

- name: Add unique overlay
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f {{ tmp_dir }}/unique-overlay.ldif"

# memberOf overlay
- name: Search Directory for memberof overlay
  shell: "ldapsearch -QLLLY EXTERNAL -H ldapi:/// -b cn=config  olcOverlay=memberof"
  register: memberof_overlay

- name: Render template memberof-overlay.ldif
  template:
    src: roles/{{role_name}}/templates/memberof-overlay.ldif
    dest: "{{ tmp_dir }}/memberof-overlay.ldif"

- name: Add memberOf overlay to openldap
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f {{ tmp_dir }}/memberof-overlay.ldif"
  when: memberof_overlay.stdout == ""

# useless, memberOf also came with refint feature
# refint refint
# - name: Add refint overlay
  # command: "ldapadd -Y EXTERNAL -H ldapi:/// -f roles/{{role_name}}/files/refint_overlay.ldif"

# - name: Search Directory for pw-sha2 overlay
  # shell: "ldapsearch -QLLLY EXTERNAL -H ldapi:/// -b cn=config  olcModuleLoad=pw-sha2"
  # register: pwsha2

# smbk5pwd overlay
- name: Render template smbk5pwd-overlay.ldif
  template:
    src: roles/{{role_name}}/templates/smbk5pwd-overlay.ldif
    dest: "{{ tmp_dir }}/smbk5pwd-overlay.ldif"

- name: Add smbk5pwd-overlay.ldif
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f {{ tmp_dir }}/smbk5pwd-overlay.ldif"

# to be fixed
# - name: "Set limitless search for repl users on primary db"
  # shell:
    # cmd: |
      # ldapmodify -Y EXTERNAL -H ldapi:/// <<EOF
      # dn: olcDatabase={1}{{ ldap_backend }},cn=config
      # changetype: modify
      # replace: olcLimit
      # olcLimit: dn.children="ou=repl,{{ ldap_basedc }}" time.soft=unlimited time.hard=unlimited size.soft=unlimited size.hard=unlimited
      # EOF
  # when: syncrepl_enabled == True

# - name: "Set limitless search for repl users on accesslog"
  # shell:
    # cmd: |
      # ldapmodify -Y EXTERNAL -H ldapi:/// <<EOF
      # dn: olcDatabase={3}{{ ldap_backend }},cn=config
      # changetype: modify
      # replace: olcLimit
      # olcLimit: dn.children="ou=repl,{{ ldap_basedc }}" time.soft=unlimited time.hard=unlimited size.soft=unlimited size.hard=unlimited
      # EOF
  # when: syncrepl_enabled == True and accesslog_enabled == True
